Repository Badwater-Apps/ethnic-cuisine-trends, pull requests merged in 2020-05, with the labels that each got.

#16 Generated time series weighted popularity values by US state
  .gitignore
  src/data/agg/cuisine-wtd-usa.csv
  src/data/ref/parsed_usa_intnt_users.csv
  src/data/ref/usa_internet_user_info.csv
  src/processing/transform.ipynb
  src/processing/weights.ipynb
Labels: PR: review needed, complexity: 3, lang: python, type: feature request

#19 Fixes #18: Initiated html, js, and css for showing plots
  src/html/index.html
  src/html/script.js
  src/html/styles.min.css
  src/html/styles.min.css.map
  src/html/styles.scss
Labels: PR: review needed

#20 Round weighted data to three decimal places
  src/data/agg/cuisine-wtd-usa.csv
  src/processing/transform.ipynb
Labels: PR: review needed, lang: python, type: enhancement
